#!/usr/bin/env bash

# Calls ctci/problem_picker.py
# MOVE THIS INTO location that is in your $PATH

# UPDATE THIS
SCRIPT_LOCATION="$HOME/src/github/johannesgiorgis/ctci/"

cd "$SCRIPT_LOCATION"

pipenv run python problem_picker.py "$@"
